// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    id "com.dorongold.task-tree" version "1.5"
    id "io.sentry.android.gradle" version "3.3.0"
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

ext {
    applicationId      = "com.studio4plus.homerplayer"
    versionName        = "1.0.10-fork-0.0.2-21API"
    versionCode        = 78
    minSdkVersion      = 21
    targetSdkVersion   = 35
    compileSdkVersion  = 35
    buildToolsVersion  = "35.0.0"
    javaVersion        = JavaVersion.VERSION_1_8
    version_appcompat  = "1.5.1"
    version_lumberjack = "5.0.3"
}
